### ISSUE TITLE
Full debugger?

### ISSUE THREAD

**Issue by Gb42** [NeilFraser/JS-Interpreter#115]
Hi,

I am using this project as a debugger of JavaScript code, I'm so happy to use the step-by-step feature, but is there an easy way to get the value of the current "node Identifier" ?
And better, is there an easy to get the values of the other variables accessibles from the current scope?

Thanks a lot for that huge work you did!

**Comment by NeilFraser** [comment]
To browse the variables, loop through the interpreter's .stateStack array, starting from the end working to the beginning.  For each state, check if it has a .scope property.  If so, then all the variables defined in that scope are in .scope.properties.

For example:
* Go to https://neil.fraser.name/software/JS-Interpreter/
* Press 'parse'.
* Press 'step' 25 times (so that you get to the loop).
* On the console, type:  myInterpreter.stateStack[4].scope  This is undefined, meaning there is no scope here.
* On the console, type:  myInterpreter.stateStack[3].scope  This is gives you the scope object for the function, use the console's inspector to look into the properties list.
* On the console, type:  myInterpreter.stateStack[0].scope  This is gives you the global scope.  This can also be accessed using: myInterpreter.global

Let me know if you need anything else.
