### ISSUE TITLE
Interpreter of whole js file?

### ISSUE THREAD

**Issue by CesMak** [NeilFraser/JS-Interpreter#125]
Is it possible to create an interpreter of a whole js file?

I tried it like this:
```
    var myCode = 'importScripts('+'libs/simact.bundle.js'+');';
    var initFunc = function(interpreter, scope) {
     // interpreter.setProperty(scope, 'url', String(location));

      var wrapper = function(text) {
        return importScripts(text);
      };
      interpreter.setProperty(scope, 'importScripts',
          interpreter.createNativeFunction(wrapper));
    };
    var myInterpreter = new Interpreter(myCode,initFunc);
```

But it does not work.
Any ideas?

**Comment by cpcallen** [comment]
In the example code, the call to `importScripts` in the interpreted code results in `importScripts` being called in the native (not interpreted) JS runtime (i.e., the same one running JS-Interpreter, which is to say directly in the browser)  This is almost certainly not what you want:

* It is dangerous, because it circumvents the sandboxing of interpreted code.
* It is not very useful, because code run by the (native) `importScripts` cannot interact with code running inside the interpreter.

You could write a version of `importScripts` which would import the scripts into the interpreter and run them there, but this can't be done by wrapping the system version of the function.

**Comment by NeilFraser** [comment]
I'd suggest:
```javascript
var wrapper = function(name) {
  var newCode = load(name); // Create a load function using XHR to get the contents of the file.
  interpreter.appendCode(newCode);
}
```
