### ISSUE TITLE
createNativeFunction calls back with pseudo array.

### ISSUE THREAD

**Issue by NAllred91** [NeilFraser/JS-Interpreter#132]
```
interpreter.setProperty(internalConsole, 'log', interpreter.createNativeFunction((message) => {
     // If message is an array, at this point it is an interpreter psuedo array and needs to be converted to a native array.
     message = interpreter.pseudoToNative(message)
})
```

When I call my native log function with an array, the callback gets called with a psuedo array.  I can get around it by calling `interpreter.pseudoToNative`, but this destroys error objects.

I'm not sure if this is expected behavior, or if the callback should be called with a native array?

**Comment by NeilFraser** [comment]
Yes, that's the expected behaviour.  Mutable objects can't be passed back and forth between the JS and interpreter environments.  You need to serialize them in some way.  JSON is the usual approach, but that doesn't handle error objects.

In the case of a log function, I'd suggest a two-part process.  Use a function called 'log' created with a polyfill inside the interpreter to stringify the argument(s), then have that function call 'log_' which is a native function that logs a single string.

If you care about hiding 'log_' from users, that can be done too: https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L569

**Comment by NAllred91** [comment]
Thanks,

Is there a risk to handling this all in the JS and not in the interpreter?  Using `interpreter.pseudoToNative` on all of the parameters coming out of the interpreter seems to be working fine, and I just use a `type of` check to deal with error objects.

I don't see any issues doing this, and its more straightforward than serializing inside the interpreter.  I just want to make sure there isn't some risk associated with this that I'm not aware of.

**Comment by NeilFraser** [comment]
No risk, if you've got code working then you're good to go.  I suggested doing it in the interpreted environment simply because it might be a bit easier than parsing pseudo object data structures externally.  But doing it externally definitely runs faster.
