### ISSUE TITLE
Why not recursive evaluation?

### ISSUE THREAD

**Issue by vasyop** [NeilFraser/JS-Interpreter#141]
Hi,

I found this project to be an excellent learning resource for compilers/interpreters. 
I have one question though: Why did you choose the iterative approach for evaluation? (apart from the obvious call stack size limitation).

It seems to me that many of the complications of switching back and forth from states and/or maintaining a step number within some states could have been avoided had you chosen the recursive approach.

Am I missing anything?

Thanks

**Comment by NeilFraser** [comment]
Yes, it would be a lot easier to store state as local variables, and recursively call the steps.  That's the way most interpreters work.  However, a unique requirement of this interpreter is the ability to execute step-by-step, with pauses in between.  Since JavaScript (the language the interpreter is written in) has no ability to suspend a running task, the only option is to store state as a data structure, and iteratively call the steps.

Good question.
