### ISSUE TITLE
Array.prototype.XXX

### ISSUE THREAD

**Issue by Hypercubed** [NeilFraser/JS-Interpreter#15]
I see in the commit history that `Array.prototype.forEach` was removed.  Also, `filter`, `map`, and `reduce` were never implemented.  Is this a design decision?  Are PR accepted if someone adds them?  Thanks.

**Comment by NeilFraser** [comment]
The forEach commit and reversion appears to have happened on jsearles's branch, both getting rolled up together in the regex patch he committed.  Don't know why he got second thoughts on forEach.

Development from Google's end has stalled simply because the interpreter currently covers 100% of what we need it to cover.  But any patches that improve the JS coverage are gratefully accepted.

**Comment by jrsearles** [comment]
Sorry - i do have forEach implemented in a separate branch, but i was struggling a bit to get filter/map/etc implemented. I didn't want to submit forEach until i had those worked out, since they are ultimately very similar.
