### ISSUE TITLE
Scope of variables [question]

### ISSUE THREAD

**Issue by fpelliccioni** [NeilFraser/JS-Interpreter#154]
Hello, 

Is is possible to know when a variable enter in its scope and when it exit?

For example, in the following code snippet ...
```
function foo(a, b) {       // 3
   var tmp = a + b;        // 4
   return tmp;
}                                  // 5

var x = 5;                    // 1
var y = 7;                    // 2
var r = foo(x, y);          //6

```
I want to know something like:
1. Local Variable named "x" introduced with value: 5
2. Local Variable named "y" introduced with value: 7
3. Parameters named "a" and "b" introduced.
4. Local Variable named "tmp" introduced...
5. Scope exit for a, b and tmp.
6. Local Variable named "r" introduced...

Thanks in advance!
Fernando.

**Comment by NeilFraser** [comment]
Interestingly, that's not actually how JavaScript works.  Due to "variable hoisting", it actually works like this (both in this interpreter, and in browser's JavaScript engines):

```
// 0
function foo(a, b) {       // 3
   var tmp = a + b;        // 4
   return tmp;
}                                  // 5

var x = 5;                    // 1
var y = 7;                    // 2
var r = foo(x, y);          //6
```

0. Global variables named "x", "y", and "r" introduced, all with value `undefined`.  Global variable named "foo" introduced, set to a function. 29 other global variables are also introduced and set: "NaN", "Infinity", "undefined", "window", "this", "self", "Function", "Object", "Array", "String", "Boolean", "Number", "Date", "RegExp", "Error", "EvalError", "RangeError", "ReferenceError", "SyntaxError", "TypeError", "URIError", "Math", "JSON", "eval", "parseInt", "parseFloat", "isNaN", "isFinite", "alert"
1. Global variable "x" set to value 5.
2. Global variable "y" set to value 7.
3. New scope.  Local variable named "a" and "b" introduced, set to 5 and 7 respectively.  Local variable named "tmp" introduced, set to `undefined`.  Local variable named "arguments" introduced and set to [5, 7].  Local variable "this" is introduced (masking the global variable of the same name) and is set to the global object (which happens to be the same value as the masked value from the global scope.
4. Local variable named "tmp" set to 12.
5. Scope exit for "a", "b", "tmp", "arguments", "this".
6. Global variable named "r" set to 12.

My point is that when you ask the interpreter for variable changes, you'll get a lot more stuff than you were expecting.  Also, 'var' statements are create (but don't define) the variable at the top of the function (or program), not when executed.

With all that out of the way, it's actually easy to get this data.  Go to the demo:
https://neil.fraser.name/software/JS-Interpreter/
Paste in the code from above, and press "Parse".
Open your browser's console.
You can step through the code to any point, then enter in the console:
`myInterpreter.getScope().properties`
That will list the names and values of the variables in the current scope.  If you are inside the function, then you will also want to look at:
`myInterpreter.getScope().parentScope.properties`
This will list the names and values of the variables in the next scope out.  If you had a function in a function, then you'd need `myInterpreter.getScope().parentScope.parentScope.properties` to reach the global scope.

Also, at any time you can type `myInterpreter.getValueFromScope('x')` to query the value of a variable, and it will work its way through the stack of scopes until if either finds "x", or hits the global scope.

Hope this points you in the right direction.

**Comment by fpelliccioni** [comment]
Oh! many thanks for your great explanation!

**Comment by livioenrico** [comment]
I tried the following lines in the JavaScript file:
```
var value = myInterpreter.getValueFromScope('Alice1')
window.chrome.webview.postMessage(value);
```
I am sure that the variable Alice1 exists because I tested it with these lines:
```
var v = workspace.getAllVariables();
    for (var i = 0; i < v.length; i++)
    {
        var n = v[i].name;
        window.chrome.webview.postMessage(n);
    }
```
But instead to get the variable value the code breaks for some error

How can I get the value of the variables ?

Thanks in advance
Livio

**Comment by livioenrico** [comment]
I tried also myInterpreter.getScope().properties in the console but I get the following error:
```
Uncaught TypeError: myInterpreter.getScope is not a function
    at <anonymous>:1:15
```

Before to test it I runned the interpreter and it is working and Hilighting blocks when I call:

`hasMoreCode = myInterpreter.step();`

**Comment by livioenrico** [comment]
It is about one week that I am trying to get variable values without any success.

Please help me.

**Comment by livioenrico** [comment]
This is an image about my experiments
![JS-TEST-1](https://user-images.githubusercontent.com/112852907/192136121-84936663-9877-4408-86e1-056c5f3b5a5d.jpg)

**Comment by NeilFraser** [comment]
@livioenrico Try using `acorn.js` and `interpreter.js` instead of the compiled `acorn-interpreter.js`.  The functions you are trying to call (e.g. getScope) are not part of the public API, so the compiler renames them to something shorter.

**Comment by livioenrico** [comment]
OK, I'll try if I can read the variables with these files.
I have already tested acorn.js and interpreter.js but using them no longer works the blocks highlighting.
Maybe I am using old versions of the files?
- acorn.js is long 67.488 bytes and contains this row: exports.version = "0.4.1";
- interpreter.js is long 154.565 bytes and no version

My application with Blockly is coming up beautiful, thanks for the great work you have done and thanks for your attention to this little problem of mine.

**Comment by livioenrico** [comment]
I tried again acorn.js and interpreter.js and perhaps with these files the problem is not the darkness of the blocks but that the interpreter no longer proceeds and immediately gives me "false" when I call: hasMoreCode = myInterpreter.step ();

**Comment by livioenrico** [comment]
After many try and errors I obtained this:
![Image2](https://user-images.githubusercontent.com/112852907/192784288-f2fcb341-bdc2-4538-826b-dfab4c22d756.png)

And then I tried to use some of those functions but without success.

**Comment by NeilFraser** [comment]
There you go. `myInterpreter.globalScope.object.properties.Alice1` is `123`.  Same for `Alice2`, `Alice3`, and `Bob1`.

**Comment by livioenrico** [comment]
Ho visto anche io che i valori sono li ma per leggerli cosa si deve scrivere?
Dopo il tuo messaggio ho provato le istruzioni seguenti ma non leggono il valore e vanno tutte in errore

var value = myInterpreter.globalScope.object.properties.Alice1;
var value = myInterpreter.globalScope.object.properties.Alice1.number;
var value = myInterpreter.globalScope.object.properties.Alice1.value;
var value = myInterpreter.globalScope.object.properties.Alice1.getValue();

Ma tu hai mai provato a leggere il valore di una variabile del JS-Interpreter ?
Se lo hai fatto mi scrivi per piacere le istruzioni che hai usato per leggere il valore ?
