### ISSUE TITLE
Can't return object with functions

### ISSUE THREAD

**Issue by KSean222** [NeilFraser/JS-Interpreter#158]
I'm trying to make an API function return an object with functions
I have a test script here: https://hastebin.com/lepuqecoli.xml
Trying to access myClass's function from within the interpreter returns undefined, but it's fine otherwise when accessing it from the interpreter or running it with javascript. How can I return an object with functions?

**Comment by cpcallen** [comment]
So it's not clear what your end goal is here, but some general advice:

* In general, it's fine to create native functions, but creating native classes is generally to be avoided because of the difficulty of doing so correctly.

* A function like `newMyClass` should only return either a primitive value or an object created using `Interpreter.prototype.createObject`, `.createObjectProto`, `.nativeToPseudo` or `.arrayNativeToPseudo`, all of which return "interpreter objects" (AKA "pseudo objects").  Returning a native object (any other kind of object) is going to violating the sandbox and probably cause crashes.

* If you need to attach data to an interpreter object, you have two choices:
   * If the data is primitive-valued, and you want it to be accessible from within the interpreter as properties, then call `Interpreter.prototype.setProperty`, passing the interpreter object, property name and primitive value.
   * For any other data—and particularly for native-object-valued data, just create a (native) property on the interpreter object.  The property can have any name except `getter`, `setter`, `properties`, `proto` or `class`.  The property will not be accessible from within the interpreter, but can be accessed from within the body of native builtin functions created using `createNativeFunction`.

In this case you should probably remove the `class` definition for `myClass`, and instead define it (using ES5 syntax) using a bit of code executed by the interpreter at startup.  Then any API methods (like `someFunction`) can be added to it by an incantation like:

```JS
var wrapper = function() {
  return "result";
}
var myClass = interpreter.getValueFromScope('myClass');
var myClassPrototype = interpreter.getProperty(myClass, 'prototype');
interpreter.setValue(myClassPrototype, 'someFunction', wrapper);
```

**Comment by KSean222** [comment]
I'm not sure I get how to define it at startup. Where would this code go?

**Comment by cpcallen** [comment]
> I'm not sure I get how to define it at startup. Where would this code go?

Wherever you like.  Probably the easiest thing to do is to prepend it to `myCode` in your example.

**Comment by KSean222** [comment]
Hmm, it's telling me that getValueFromScope is not a function. . .

**Comment by KSean222** [comment]
Okay, switching to the uncompressed versions fixed that. However, now I'm not sure how to define my class. Prepending the code to `myCode` tells me that it is not defined. I tried putting the constructor function as the code and running it first before appending `myCode`, but it doesn't seem to work either. How can I define it?
