### ISSUE TITLE
Error: Expecting original AST to start with a Program node.

### ISSUE THREAD

**Issue by dieudv** [NeilFraser/JS-Interpreter#159]
I encountered a case like this:

```javascript
initApi = function (interpreter, scope) {
    var wrapper = function (text) {
        text = text ? text.toString() : '';
        return interpreter.createPrimitive(alert(text));
    };
    interpreter.setProperty(scope, 'alert', interpreter.createNativeFunction(wrapper));
}

var code = "function a(){alert('ok');}function b(){a();};"
var interpreter = new Interpreter(code, initApi);
interpreter.appendCode("b();");
interpreter.run(); // ok

interpreter.appendCode("b();");
interpreter.run(); // ok

// If i append an error code such as a func not yet defined 
interpreter.appendCode("c();");
interpreter.run(); // ReferenceError: c() is not defined (sure, of course)

// But if I append a correct code after that this error will appear
interpreter.appendCode("b();");
// Error: Expecting original AST to start with a Program node.
// I can't appendCode anymore
```

**Comment by NeilFraser** [comment]
Right, this is equivalent to placing the following code into a JS file and executing it:
```
function a(){alert('ok');}function b(){a();};
b();
b();
c();
b();
```
JavaScript will never reach the final `b();` since a fatal error was thrown.  Thus the existing behaviour is intended.  Though the error message is basically meaningless and needs to be changed to "Can't append code to program which has thrown an error and exited.", or something to that effect.

However, one could argue that each `appendCode` snippet is a separate script tag, rather than an addition to a JS file.  Under that interpretation, each snippet should be executed.

Hmm, no clear answer here.  @cpcallen, got any thoughts on this?

**Comment by cpcallen** [comment]
Two thoughts:

1. It's reasonable that a function named `appendCode` fails in this situation, but if so it should arguably also fail if execution of the program has terminated normally, too!
1. It ought to be possible to run another program in the same context (global environment) regardless of how the previous program terminated.  If such a function can legally be called before the existing program has terminated then `appendCode` is not a terrible name for it—but it could alternatively be named `newProgram` or the like, and only be permitted once the existing program has completed.

I don't remember the details, but presumably JS interpreter avoids popping the Program node off the state stack when doing a normal termination, but does pop it when unwinding.  It seems to me that it would be better if it were consistent about that.

**Comment by NeilFraser** [comment]
Thanks @cpcallen.  I think the deciding factor between the two interpretations of `appendCode` (all pieces are the same file, vs each piece is a separate script) is that there's no hoisting across the pieces.
```
foo();
function foo() {}
```
The above code is perfectly valid in a single file.  But if each line were in a separate script tag, the first line would fail.  That's consistent with the way appendCode must behave since the JS-Interpreter does not currently have a time machine to know what future code will be appended.

And more practically, I can't think of a reason why real-world users would want appendCode to fail after an uncaught throw.

Ok, changing the behaviour...

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
