### ISSUE TITLE
REGEXP_Mode not working in compressed library

### ISSUE THREAD

**Issue by robertmuehsig** [NeilFraser/JS-Interpreter#164]
We use you library in a "embedded scripting environment" and recently needed to support good old IE11 and we used the most recent "acorn_interpreter.js" file. We quickly discovered this (solved) issue #152 and set to "REGEXP_Mode" switch to 1.

Unfortunatly the "REGEXP_Mode" seems to be ignored, even if we set it to 0, the code "worked", but should have failed.

We are not 100% sure, but it looks like that the JS minimizer seems to omit this "REGEXP_Mode" property. 

As a workaround we now use the non compressed files which works for us.

**Comment by cpcallen** [comment]
Could it just be that `acorn_interpreter.js` is out of date and needs to be rebuilt?

**Comment by robertmuehsig** [comment]
Looks fresh to me: 
![image](https://user-images.githubusercontent.com/756703/67948721-973e4080-fbe6-11e9-9435-1e4f27b513ac.png)

But I don't know which tool/settings @NeilFraser used to compress those js files.

**Comment by NeilFraser** [comment]
My fault, the Closure compiler was renaming the property.  Thus to set `REGEXP_MODE`, one would have had to set `X` instead.  I've fixed the problem here: https://github.com/NeilFraser/JS-Interpreter/commit/3de0435d29802fbb50b796ae01f3239a9e1fed7f

Side note: Much confusion arose in debugging this because I was unable to locate the timeout constant of `1000` in the compressed file.  Eventually I discovered that Closure compiler was changing this to `1E3`.  This saves one byte.  Wow.  I wonder if it is a net saving after gzip.

**Comment by robertmuehsig** [comment]
Maybe stupid question, but do I need to change this code:

```
var interpreter = new Interpreter(runtimeJS, initializeRuntime);
interpreter .REGEXP_MODE = 1;
```
to
```
var interpreter = new Interpreter(runtimeJS, initializeRuntime);
interpreter['REGEXP_MODE'] = 1;
```

or is 'REGEX_MODE' still treated as a property?

**Comment by NeilFraser** [comment]
No need to change anything on your side.  Either `interpreter.REGEXP_MODE` or `interpreter['REGEXP_MODE']` will work in your code.  They are usually completely equivalent, but in interpreter.js the latter is a signal to the Closure Compiler that it is not allowed to rename the property to something shorter.
