### ISSUE TITLE
Unexpected token error 

### ISSUE THREAD

**Issue by nitesh-1092** [NeilFraser/JS-Interpreter#213]
When I run interpreter on this code, My react application shows unexpected token error and crashes. Is there any way to stop my app from crashing? Please help me. I know it's a syntax error but I don't want any react app to crash. Is there any way to spot the error first. React doesn't supports try/catch. I am adding Blockly to my react app and to run the JS code I am using js-interpreter. 

code = var i; for (i = 1; i <= 10; i++) { }
const myInterpreter = new Interpreter(code);
myInterpreter.run()

![image](https://user-images.githubusercontent.com/21355238/123206125-c64ea780-d4d8-11eb-82eb-cb9ba80417ca.png)

**Comment by NeilFraser** [comment]
> React doesn't supports try/catch.

I have no experience with React, so this limitation is news to me.  But a short Google search seems to indicate that there's now something called [Error Boundaries](https://reactjs.org/docs/error-boundaries.html).  Could this work for you?

If not, I suggest discussing the issue with people who know React (maybe Stack Overflow).  The JS-Interpreter project doesn't have the required knowledge for your chosen framework.

That said, do update this bug with what you find, so that the next React user can be helped.  Thanks!
