### ISSUE TITLE
The JS-Interpreter Self-interpreter Demo does not work

### ISSUE THREAD

**Issue by ChrisAcrobat** [NeilFraser/JS-Interpreter#229]
[JS-Interpreter Self-interpreter Demo](https://neil.fraser.name/software/JS-Interpreter/demos/json.html)
1. Follow the instructions.
1. Returns `acorn.js:229 Uncaught SyntaxError: Unexpected token (123:71)` at `acorn.js:229`.

**Comment by cpcallen** [comment]
Hmm.  Seems the compiler is generating ES6; the offending expression is: `b={EvalError,RangeError,ReferenceError,SyntaxError,TypeError,URIError}`.

**Comment by cpcallen** [comment]
I note that this bug seems to have been introduced in commit 145805f.

**Comment by NeilFraser** [comment]
Fixed.  The compiled version used to be generated using the online [Closure Compiler Service](https://closure-compiler.appspot.com/home).  However, recently this has stopped working for large compilations, due to App Engine runtime limits.  I switched to using the downloadable JAR file, but neglected to add the ES5 output flag.

Thanks for reporting this regression.
