### ISSUE TITLE
This repo is being mocked in r/ProgrammerHumor.

### ISSUE THREAD

**Issue by alixsep** [NeilFraser/JS-Interpreter#242]
This is the link to the post: https://www.reddit.com/r/ProgrammerHumor/comments/10cmtz4/why_are_programmers_like_this/
![image](https://user-images.githubusercontent.com/59757582/212566121-63bfab20-8d38-48bf-b928-d0855c4144c7.png)

I have no intention to any means by opening this issue. Doing it just so you don't miss it.

**Comment by NeilFraser** [comment]
Well, that's fun.  Thanks for pointing it out.

For anyone on that thread who is interested, the point of this repo is to:

a) securely sandbox JavaScript so that untrusted code may be safely executed.
b) JavaScript can be multi-threaded.
c) code can be executed step-by-step with pauses (useful in real-time games).
d) execution may be serialized and saved, then restored and resumed at a later date.
e) code can be executed backwards.

JS-Interpreter quietly powers a lot of applications out there.  Especially at Google.
