### ISSUE TITLE
Support for serializing current state

### ISSUE THREAD

**Issue by dested** [NeilFraser/JS-Interpreter#27]
Do you think it would be possible to halt execution halfway through a program, and serialize the entire state of the program, so it may be resumed at a later date? If so would you mind letting me know some of the pitfalls I would encounter so I may expedite implementing this feature?

**Comment by BrownBear2** [comment]
I don't know what you want to achieve with the serialization, but with the new async function support, you can easily halt the interpreter and resume it at any later time by calling run() again.

**Comment by dested** [comment]
The goal is to resume the application at a later day potentially, or being able to close the broswer/node and restarting the app right where it left off. I appreciate that it is an uncommon usecase, but do you think it's feasible to accomplish?

**Comment by BrownBear2** [comment]
From a rather quick glance over the interpreter it looks to me that, if you reinitialize your interpreter again the same way as before (pass same native functions etc.) you should be able rather easily to replace the internal stack with the one you serialized before using JSON or so.

**Comment by dested** [comment]
So you feel the only field that will need to be serialized is stateStack on interpreter? I will try to mock this up and see if there are any issues.

Thanks for the help!

**Comment by BrownBear2** [comment]
I looked at it a bit more. One issue is to replace all the conversion / other methods (especially native ones) on pseudo variables. It should be doable, but it's definitely not easy. The other thing is that scopes and ast nodes both have cross references to other scopes/nodes, which you would have to handle when serializing. That part shouldn't be too hard.

**Comment by NeilFraser** [comment]
This is a really interesting problem.  Basically all one needs to do is serialize stateStack, but the catch is that there are shared object references (pointers to the same object can appear in multiple places) and there are functions on objects.  So JSON is out of the question.  I'll work on it this week.

**Comment by shootingsyh** [comment]
Hi @NeilFraser do you have more details about how to do this now? I'm also interested in doing the serialization and want to hear some ideas. Thanks!

**Comment by NeilFraser** [comment]
I got distracted by higher priority stuff (like lastIndexOf is broken on lists), so haven't started this yet.

The basic premise is that the stateStack data structure is the only thing that needs to be saved (ast is never used).  Unfortunately it can't just be JSONed for two reasons:

One reason is that there are common objects in the structure, so if object A has objects B and C in properties, and both B and C have object D in a property, a trip through JSON would end up creating two separate D objects that are no longer linked.  So the serialization process needs to give IDs to every object and store the objects in a separate map.

Another reason is that all objects in JSON are {}, whereas we require than objects be of particular classes, such as Interpreter.Primitive and Interpreter.Object so that they can have access to methods like toString.  So the serialization format needs to make a note of the object types so that the correct constructors can be called when deserializing.

And the final issue is that native functions created on init.  The easiest way deal with them is to skip them when serializing.  Then after loading the partially serialized state, call init to rebuild the incomplete objects.  In this case all the init functions (such initMath) would need to check the global scope to see if the objects they are configuring are already defined and use those objects rather than always creating new objects.  This is a very simple change.

**Comment by NeilFraser** [comment]
I was wrong with regards to handling native functions.  The issue is that native functions can move around:
```
var temp = Math.max;
Math.max = Math.min;
Math.min = temp;
```
Thus one can't rely on the init functions to setup the naive functions where they should be.

One alternative is to store and serialize the code of the native functions so that they may be rebuilt.  This does not work since the function could be a closure, linked to the scope of something outside the interpreter.

So that leaves one option: deterministically give each native function an ID, maintain a map of native functions, store each ID in the serialization, then when restoring state run the init functions to regenerate all the native functions, destroy the scope that init creates, and build a new scope based on the serialization.  That should work properly.

**Comment by dested** [comment]
Hey @NeilFraser, just checking on the status of this. Is there any heavy lifting that you could use a hand on to finalize this feature? Any blockers you encountered which would make this impossible?

**Comment by dested** [comment]
Hey @NeilFraser, just pinging again to see if you had any further input on this?

**Comment by NeilFraser** [comment]
Complete: ebaf7a156e04fae9cb65f15c9a12fe4d102d877f
Demo: https://neil.fraser.name/software/JS-Interpreter/demos/serialize.html

**Comment by dested** [comment]
I just wanted to stop by and say thank you. This is incredible, and is a huge selling feature for the project. 

Truly, thank you.

**Comment by NeilFraser** [comment]
@dested My pleasure.  Sorry it took so long to get to this.
Just pushed [an update](c90c80a1ea0cfea1ff383f60d1865bdc612f7821) which fixes serialization of NaN, -0, Infinity and -Infinity (four numbers which don't round-trip through JSON correctly).

**Comment by NeilFraser** [comment]
FYI: The serialization format has changed (and is liable to keep changing every release).  It is now one third the size it used to be.
