### ISSUE TITLE
Regex code block not evaluated inside background script for chrome web extension

### ISSUE THREAD

**Issue by itsdivyanshjain** [NeilFraser/JS-Interpreter#282]
I want to utilize `acorn_interpreter` for js evaluation inside chrome web extension `background.js` (service worker) file. Download the `acorn_interpreter.js` and then add below line at the end `export default Interpreter;`

Now below code is working in `background.js`

```
import Interpreter from './acorn_interpreter.js'
var myInterpreter = new Interpreter('6 * 7');
myInterpreter.run();
alert(myInterpreter.value);
```

But regex related code is not working

```
import Interpreter from './acorn_interpreter.js'
var myInterpreter = new Interpreter('a=new RegExp("hello");b=new RegExp("world");  c="hello world"');
myInterpreter.appendCode("a.test(c) && b.test(c)")
myInterpreter.run();
alert(myInterpreter.value);
```

showing this error:
<img width="634" alt="image" src="https://github.com/user-attachments/assets/d01d3b1c-b5fc-4fd5-a30b-37d135009af3">  

Remember above mentioned code does work fine when i use same script for normal website purpose or as content script for webextension.

**Comment by NeilFraser** [comment]
I'm not at a computer right now, but check this page out if you haven't seen it yet:
https://neil.fraser.name/software/JS-Interpreter/demos/regexp.html

Will check in later today.

**Comment by NeilFraser** [comment]
Ok, I've decompiled the traceback:
```
populateError: 2362
throwException: 3307
maybeThrowRegExp: 2444
exec: 2081
```

From this I can tell that it is trying to execute a RegExp, failing, then throwing an error to inform you of this, then failing to throw.  Thus there are two issues here.

The side issue is that the error is failing to throw which made this whole problem very cryptic.  I'll look into this.

The root issue is that it is unable to execute a RegExp.  It looks like it is trying to create a Web Worker (because REGEXP_MODE is 2), failing, then giving up.  Thus you have three choices:

1. Set REGEXP_MODE to 0 and don't support regular expressions in your extension.
2. Set REGEXP_MODE to 1 and understand the risks of pathological regular expressions.  Depending on your application, this may or may not be an issue -- read up on it here: https://neil.fraser.name/software/JS-Interpreter/demos/regexp.html
3. Leave REGEXP_MODE at 2 (the default) and enable Web Workers for your extension.  Some discussion I found on this is here: https://stackoverflow.com/questions/32853359/using-web-workers-with-chrome-extension

I'll go look into why it was throwing an error while trying to throw an error...

**Comment by itsdivyanshjain** [comment]
> Ok, I've decompiled the traceback:
> 
> ```
> populateError: 2362
> throwException: 3307
> maybeThrowRegExp: 2444
> exec: 2081
> ```
> 
> From this I can tell that it is trying to execute a RegExp, failing, then throwing an error to inform you of this, then failing to throw. Thus there are two issues here.
> 
> The side issue is that the error is failing to throw which made this whole problem very cryptic. I'll look into this.
> 
> The root issue is that it is unable to execute a RegExp. It looks like it is trying to create a Web Worker (because REGEXP_MODE is 2), failing, then giving up. Thus you have three choices:
> 
> 1. Set REGEXP_MODE to 0 and don't support regular expressions in your extension.
> 2. Set REGEXP_MODE to 1 and understand the risks of pathological regular expressions.  Depending on your application, this may or may not be an issue -- read up on it here: https://neil.fraser.name/software/JS-Interpreter/demos/regexp.html
> 3. Leave REGEXP_MODE at 2 (the default) and enable Web Workers for your extension.  Some discussion I found on this is here: https://stackoverflow.com/questions/32853359/using-web-workers-with-chrome-extension
> 
> I'll go look into why it was throwing an error while trying to throw an error...

Thanks for update @NeilFraser. Yes, REGEXP_MODE = 1 working in my case, also i believe risk would be acceptable in my case. But is there a way timeout regex evaluation.

**Comment by NeilFraser** [comment]
Found and fixed the side issue.  The compiler was renaming a property (as it should), but I was checking for the property by hard-coded name.  With that resolved, now the error thrown should be much more descriptive: `Uncaught Error: Regular expressions not supported: /hello/`

As for is there a way to timeout regex evaluation, yes.  It involves running the regexp in a separate thread (a web worker) and monitoring its execution time.  That's REGEXP_MODE 2.  Without the thread, it will simply block the browser's interpreter.

Note that pathological regular expressions may not be an issue for you at all.  To exploit them, a malicious user needs to be able to specify both the string and the regular expression.  And the result is just a locked browser (denial of service), not a security leak.

**Comment by itsdivyanshjain** [comment]
@NeilFraser just a suggestion, docs shows that there are regex mode but doesn't show how to set them. I have to view source of demo file to get this info. It might be obvious but still ambiguous for an end user.

Adding below line will be very helpful
`myInterpreter.REGEXP_MODE = 1;`

https://neil.fraser.name/software/JS-Interpreter/docs.html
https://neil.fraser.name/software/JS-Interpreter/demos/regexp.html

**Comment by NeilFraser** [comment]
Good point.  Done.
